version: '3'
services:
  nginx:
    image: wechain/nginx-proxy-certbot
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    environment:
      NGINX_PROXY_PASS: |
        https://app.steem.racing -> http://larden:3000
        https://devlab.steem.racing -> http://portainer:9000
        https://steem.racing -> http://condenser:8080

      CERTBOT_EMAIL: anybucket@outlook.com
      CERTBOT_ARGS: --dry-run
